#!/bin/bash
#
# this is a base script for the Linux 101 lessons

# This function will say what actions is available
# by default the available actions are launch,clean and rate
# but if you don't need the lesson to be rated just comment out
# rate echo
get_action(){
	echo "launch"
	echo "clean"
	echo "rate"
}

# Score Variable
SCORE=1

# Print Success
success_output(){
	printf "\033[1;32mSuccess\033[0m\n"
}

# Print Error
error_output(){
  printf "\033[1;31mError\033[0m\n"
}

# Print Pass
pass_output(){
	printf "\033[1;32mPass\033[0m\n"
}

# Print Failed
failed_output(){
  printf "\033[1;31mFailed\033[0m\n"
  SCORE=`expr $SCORE - 1`
}

check_file(){
	md5sum $1 | awk {'print $1'}
}

test_file(){
	if [ -e $1 ]
        then
                if [ `check_file $1` = `check_file $2` ]
                then
                        pass_output
                else
                        failed_output
                fi
        else
                failed_output
        fi
}

remove_all(){
	if [ -d $1 ]
        then
            rm -rf $1
	elif [ -e $1 ]
	then
            rm -f $1
	fi
}


# This function should prepare the environment for the task
launch_script(){
	echo -n "Creating example files........."
	touch /home/student/file1 /home/student/file2 /home/student/file3 &> /dev/null && success_output || error_output
	echo -n "Creating example directories..."
	mkdir /home/student/dir1 /home/student/dir2 /home/student/dir3 &> /dev/null && success_output || error_output
}

# This function should cleanup the environment for next tasks
clean_script(){
  	echo -n "Removing exercise files........"
	remove_all dir1 && remove_all dir2 && remove_all file1 && remove_all file2 && remove_all file3 && remove_all  dir3 && remove_all user && remove_all directoryfile && remove_all variable && success_output || error_output

}

# This function should rate the work of the student
rate_script(){
	echo -n "Created a file named linux.........."
	test -e /home/student/dir1/linux && pass_output || failed_output
	echo -n "Remove dir2 directory..............."
	test -d /home/student/dir2 && failed_output || pass_output
	echo -n "Created activityA file in dir3......"
	test -e /home/student/dir3/activityA && pass_output || failed_output
	echo -n "Created activityJ file in dir3......"
	test -e /home/student/dir3/activityJ && pass_output || failed_output
	echo -n "Created activityC file in dir3......"
        test -e /home/student/dir3/activityC && pass_output || failed_output
	echo -n "Remove file1........................"
        test -e /home/student/file1 && failed_output || pass_output
	echo -n "Remove file3........................"
	test -e /home/student/file3 && failed_output || pass_output
	echo -n "Edited contents of file2............"
	cat /etc/hostname > /tmp/file2
	echo "I am a Linux lover" >> /tmp/file2
	test_file /home/student/file2 /tmp/file2
	echo -n "Redirected output to user file......"
	whoami > /tmp/user
	test_file /home/student/user /tmp/user
	echo -n "Redirected output to variable file.."
	ls /var > /tmp/variable
	test_file /home/student/variable /tmp/variable
	echo -n "Redirected output to directoryfile.."
	pwd > /tmp/directoryfile
	test_file /home/student/directoryfile /tmp/directoryfile
	printf "\nOVERALL............................."
	if [ $SCORE -eq 1 ]
	then
		pass_output
	else
		failed_output
	fi
	rm /tmp/directoryfile /tmp/user /tmp/variable /tmp/file2
}
# This taps which method to use according to which action he chosed
script_actions(){
  if [ -z "$1" ]
  then
        echo "No action supplied!"
  elif [ "$1" = "launch" ]
  then
        launch_script
  elif [ "$1" = "clean" ]
  then
      	clean_script
  elif [ "$1" = "rate" ]
  then
	rate_script
  fi
}

# Check the action argument
check_first_argument(){
  if [ -z "$1" ]
  then
	echo "No action supplied!"
  elif [ "$1" = "action" ]
  then
	get_action
  else
	script_actions $1
  fi
}

# Main function
main(){
	check_first_argument $1
}

# Execute main function
main $1
